version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    #volumes: 
    #  - db:/var/lib/postgresql/data
  api:
    container_name: fastapi
    build:
      context: .
      #target: production
    #image: fastapi
    restart: always
    depends_on:
      - db
    ports:
      - 80:80
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      DB_TYPE: postgresql
      DB_PORT: 5432
      ACCESS_TOKEN_ALGORITHM: HS256
      ACCESS_TOKEN_SECRET_KEY: ccf0c783b343a6ba5c1fe2cbd2072ad0c96aa7a2f76bd06a1d1d1c648926e46c
      ACCESS_TOKEN_EXPIRE_MINUTES: 120
    links:
      - db
   #volumes:
   #  - './:/src'
#volumes:
#  db:
#    driver: local
